### ISSUE TITLE
Create a shared Dev Spaces cluster for all platform users

### ISSUE THREAD

**Issue by davgordo** [contract-first-idp/platform-components#18]
Platform-wide, shared Dev Spaces cluster 

Acceptance cirteria:
- A Helm chart is provided to represent the Dev Spaces cluster instance
- An ArgoCD Application configuration included in the overall platform manifest
- Any secret values are provided by configurable values in the root platform ArgoCD Application (argocd/platform-root.yaml)

**Comment by davgordo** [comment]
@smongiar and I were talking through Dev Spaces ideas a little. It might be good to start simple with this platform-wide shared Dev Spaces environment approach as an MVP.

**Comment by smongiar** [comment]
https://github.com/contract-first-idp/platform-components/pull/30
